n4dev:
    collector:
        version: 1.0.0-dev
spring:
    security:
        user:
            name: collector
            password: collector
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: password
        data: schema.sql
    h2:
        console:
            enabled: true
            path: /h2